### ISSUE TITLE
Crash on android with a simple video/cocktail app

### ISSUE THREAD

**Issue by zabojad** [nmehost/nme#10]
Hi Hugh,

I'm trying to run a simple video app made with Cocktail but it crashes when starting with the below output:

```
BUILD SUCCESSFUL
Total time: 7 seconds
1614 KB/s (9102507 bytes in 5.507s)
    pkg: /data/local/tmp/MyApp-debug.apk
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
Starting: Intent { act=android.intent.action.MAIN cmp=wwx.myapp/.MainActivity }
--------- beginning of /dev/log/main
D/GameActivity( 1220): ==== onCreate ===== wwx.myapp.MainActivity@b3d1cb80
D/AndroidRuntime( 1220): Shutting down VM
W/dalvikvm( 1220): threadid=1: thread exiting with uncaught exception (group=0xb3a61b90)
--------- beginning of /dev/log/system
E/AndroidRuntime( 1220): FATAL EXCEPTION: main
E/AndroidRuntime( 1220): Process: wwx.myapp, PID: 1220
E/AndroidRuntime( 1220): java.lang.UnsatisfiedLinkError: Couldn't load nme from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/wwx.myapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/wwx.myapp-1, /system/lib]]]: findLibrary returned null
E/AndroidRuntime( 1220):    at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime( 1220):    at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 1220):    at org.haxe.nme.GameActivity.onCreate(GameActivity.java:126)
E/AndroidRuntime( 1220):    at android.app.Activity.performCreate(Activity.java:5243)
E/AndroidRuntime( 1220):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 1220):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
E/AndroidRuntime( 1220):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
E/AndroidRuntime( 1220):    at android.app.ActivityThread.access$700(ActivityThread.java:135)
E/AndroidRuntime( 1220):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
E/AndroidRuntime( 1220):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1220):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1220):    at android.app.ActivityThread.main(ActivityThread.java:4998)
E/AndroidRuntime( 1220):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1220):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1220):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
E/AndroidRuntime( 1220):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
E/AndroidRuntime( 1220):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  404):   Force finishing activity wwx.myapp/.MainActivity
I/WindowManager(  404): Screenshot max retries 4 of Token{b4166ed8 ActivityRecord{b3f679f0 u0 wwx.myapp/.MainActivity t7 f}} appWin=Window{b3f47570 u0 Starting wwx.myapp} drawState=4
W/WindowManager(  404): Screenshot failure taking screenshot for (800x1280) to layer 21010
W/ActivityManager(  404): Activity pause timeout for ActivityRecord{b3f679f0 u0 wwx.myapp/.MainActivity t7 f}
I/Choreographer(  404): Skipped 37 frames!  The application may be doing too much work on its main thread.
E/WindowManager(  404): Starting window AppWindowToken{b4147458 token=Token{b4166ed8 ActivityRecord{b3f679f0 u0 wwx.myapp/.MainActivity t7}}} timed out
W/ActivityManager(  404): Activity destroy timeout for ActivityRecord{b3f679f0 u0 wwx.myapp/.MainActivity t7 f}
```

My local setup is

```
haxelib list
cocktail: [dev:/Users/thomasfetiveau/wksp_cocktail/cocktail]
format: 3.0.4 [3.0.5]
haxelib_client: 3.1.0-rc.3 [3.1.0-rc.4]
hxcpp: [3.1.30]
hxlibc: [1.1.4]
nme-state: [1.2.4]
nme: [5.0.37]
svg: [1.0.7]
```

Any idea about the cause of this ?

Thanks

Thomas

**Comment by hughsando** [comment]
Hi,
It looks like you have an old version of "myapp" installed, that somehow
has a newer build number.
You should use be able to uninstall the old one, or change th e"package" in
the build.nmml file to something new.
Hugh

**Comment by zabojad** [comment]
Hi Hugh !

I both changed the package of my app in the .nmml file and manually uninstall the app in the Android emulator. I keep getting the same crash when the app starts on the emulator:

```

debug:

BUILD SUCCESSFUL
Total time: 6 seconds
1863 KB/s (9102512 bytes in 4.769s)
    pkg: /data/local/tmp/MyApp-debug.apk
Success
Starting: Intent { act=android.intent.action.MAIN cmp=mycomp.myapp/.MainActivity }
--------- beginning of /dev/log/main
I/Choreographer(  364): Skipped 34 frames!  The application may be doing too much work on its main thread.
D/GameActivity( 1202): ==== onCreate ===== mycomp.myapp.MainActivity@b3d45470
D/AndroidRuntime( 1202): Shutting down VM
W/dalvikvm( 1202): threadid=1: thread exiting with uncaught exception (group=0xb3a89b90)
--------- beginning of /dev/log/system
E/AndroidRuntime( 1202): FATAL EXCEPTION: main
E/AndroidRuntime( 1202): Process: mycomp.myapp, PID: 1202
E/AndroidRuntime( 1202): java.lang.UnsatisfiedLinkError: Couldn't load nme from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/mycomp.myapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/mycomp.myapp-1, /system/lib]]]: findLibrary returned null
E/AndroidRuntime( 1202):    at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime( 1202):    at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 1202):    at org.haxe.nme.GameActivity.onCreate(GameActivity.java:126)
E/AndroidRuntime( 1202):    at android.app.Activity.performCreate(Activity.java:5243)
E/AndroidRuntime( 1202):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 1202):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
E/AndroidRuntime( 1202):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
E/AndroidRuntime( 1202):    at android.app.ActivityThread.access$700(ActivityThread.java:135)
E/AndroidRuntime( 1202):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
E/AndroidRuntime( 1202):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1202):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1202):    at android.app.ActivityThread.main(ActivityThread.java:4998)
E/AndroidRuntime( 1202):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1202):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1202):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
E/AndroidRuntime( 1202):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
E/AndroidRuntime( 1202):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  364):   Force finishing activity mycomp.myapp/.MainActivity
I/WindowManager(  364): Screenshot max retries 4 of Token{b403c978 ActivityRecord{b3f19928 u0 mycomp.myapp/.MainActivity t8 f}} appWin=Window{b3f590f8 u0 Starting mycomp.myapp} drawState=4
W/WindowManager(  364): Screenshot failure taking screenshot for (800x1280) to layer 21010
W/ActivityManager(  364): Activity pause timeout for ActivityRecord{b3f19928 u0 mycomp.myapp/.MainActivity t8 f}
```

Here is my nme.nmml file:

```
<?xml version="1.0" encoding="utf-8"?>
<project>

    <app main="myapp.App" path="bin/export" file="MyApp"/>
    <meta title="MyApp" package="mycomp.myapp" version="1.0.0" company="My Company" />
    <window width="640" height="480" fps="30" resizable="true" background="0x000000" alphaBuffer="true"  />

    <classpath name="src" />

    <haxelib name="nme" />
    <haxelib name="Cocktail" />

    <assets path="app" include="*" rename="" />

    <ndll name="std" />
    <ndll name="regexp" />
    <ndll name="zlib" />
    <ndll name="nme" haxelib="nme" />

    <compilerflag name="--remap js:cocktail" />

</project>
```

Could there be another reason for this crash ?

Thomas

**Comment by hughsando** [comment]
It looks like the nme.dll or ApplicationMain could not be loaded for some
reason - not there, or maybe wrong architecture (maybe th e emulator needs
x86?)  You can put on -debug and it should print out the libraries it is
trying to load.

**Comment by zabojad** [comment]
Hi Hugh !

This is what I get with the -debug flag:

```

-post-build:

debug:

BUILD SUCCESSFUL
Total time: 8 seconds
1573 KB/s (9933670 bytes in 6.165s)
    pkg: /data/local/tmp/MyApp-debug.apk
Success
Starting: Intent { act=android.intent.action.MAIN cmp=mycomp.myapp/.MainActivity }
--------- beginning of /dev/log/main
D/GameActivity( 1065): ==== onCreate ===== mycomp.myapp.MainActivity@b3db9840
V/GameActivity( 1065): Loading nme...
D/AndroidRuntime( 1065): Shutting down VM
W/dalvikvm( 1065): threadid=1: thread exiting with uncaught exception (group=0xb3b00b90)
--------- beginning of /dev/log/system
E/AndroidRuntime( 1065): FATAL EXCEPTION: main
E/AndroidRuntime( 1065): Process: mycomp.myapp, PID: 1065
E/AndroidRuntime( 1065): java.lang.UnsatisfiedLinkError: Couldn't load nme from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/mycomp.myapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/mycomp.myapp-1, /system/lib]]]: findLibrary returned null
E/AndroidRuntime( 1065):    at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime( 1065):    at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 1065):    at org.haxe.nme.GameActivity.onCreate(GameActivity.java:126)
E/AndroidRuntime( 1065):    at android.app.Activity.performCreate(Activity.java:5243)
E/AndroidRuntime( 1065):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 1065):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
E/AndroidRuntime( 1065):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
E/AndroidRuntime( 1065):    at android.app.ActivityThread.access$700(ActivityThread.java:135)
E/AndroidRuntime( 1065):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
E/AndroidRuntime( 1065):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1065):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1065):    at android.app.ActivityThread.main(ActivityThread.java:4998)
E/AndroidRuntime( 1065):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1065):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1065):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
E/AndroidRuntime( 1065):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
E/AndroidRuntime( 1065):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  361):   Force finishing activity mycomp.myapp/.MainActivity
I/Choreographer(  361): Skipped 41 frames!  The application may be doing too much work on its main thread.
D/gralloc (   49): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  (   49): called unimplemented OpenGL ES API
E/libEGL  (   49): called unimplemented OpenGL ES API
E/libEGL  (   49): called unimplemented OpenGL ES API
E/libEGL  (   49): called unimplemented OpenGL ES API
E/SurfaceFlinger(   49): glCheckFramebufferStatusOES error -502906978
E/SurfaceFlinger(   49): got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
E/libEGL  (   49): called unimplemented OpenGL ES API
E/libEGL  (   49): called unimplemented OpenGL ES API
W/WindowManager(  361): Screenshot failure taking screenshot for (266x425) to layer 21010
I/ARMAssembler(   49): generated scanline__00000077:03515104_00009002_00000000 [127 ipp] (149 ins) at [0xb5eea680:0xb5eea8d4] in 0 ns
D/dalvikvm(  361): GC_FOR_ALLOC freed 161K, 10% free 5838K/6456K, paused 397ms, total 402ms
I/dalvikvm-heap(  361): Grow heap (frag case) to 6.247MB for 500416-byte allocation
D/dalvikvm(  361): GC_FOR_ALLOC freed 8K, 10% free 6319K/6948K, paused 206ms, total 206ms
I/Choreographer(  361): Skipped 49 frames!  The application may be doing too much work on its main thread.
W/ActivityManager(  361): Activity pause timeout for ActivityRecord{b4024ba8 u0 mycomp.myapp/.MainActivity t3 f}
E/WindowManager(  361): Starting window AppWindowToken{b40fb528 token=Token{b407bbd8 ActivityRecord{b4024ba8 u0 mycomp.myapp/.MainActivity t3}}} timed out
W/ActivityManager(  361): Activity destroy timeout for ActivityRecord{b4024ba8 u0 mycomp.myapp/.MainActivity t3 f}
```

It's not related to the video as I have removed it from my app.

Could it be because of "called unimplemented OpenGL ES API" ?

What can I do about it ? Should I launch the emulator with specific options ?

Thanks

Tom

**Comment by hughsando** [comment]
Hi,
It looks like the device only supports opengl1.  Is it an emulator?  I know some did not support opengles2.  You could try "bluestacks" which is more like a virtual machine than an emulator.
Is this one sorted now?  I'm closing this repo and moving to https://github.com/haxenme/nme, so please reissue there if it is still a problem.
